pointcloud_topic:
    camera_topic: /camera/depth/color/points

reference_frame:
    frame_id: base_link
    
transform:
    position:
        x: -0.3
        y: 0.0
        z: 1.45
    orientation:
        roll: -1.849253
        pitch: 0.0
        yaw: -1.57

voxel_grid:
    x: 0.02
    y: 0.02
    z: 0.02
    enable: false
    
pass_through:
    x_min: 0.0
    x_max: 3.0
    x_enable: true
    y_min: -2.0
    y_max: 2.0
    y_enable: false
    z_min: 0.15
    z_max: 3.0
    z_enable: true

segmentation:
    distance_threshold: 0.01
    enable: false
    
outlier_removal:
    meanK: 50
    standard_dev_mult: 1.0
    enable: true
    
cluster_extraction:
    cluster_tolerance: 0.06
    min_cluster_size: 500
    max_cluster_size: 25000
    enable: true