voxel_grid:
    x: 0.05
    y: 0.05
    z: 0.05
    enable: false

pass_through:
    z_min: 0.0
    z_max: 1.0
    enable: true

segmentation:
    distance_threshold: 0.01
    enable: true
    
outlier_removal:
    meanK: 50
    standard_dev_mult: 1.0
    enable: true
    
cluster_extraction:
    cluster_tolerance: 0.02
    min_cluster_size: 1000
    max_cluster_size: 25000
    enable: true
    
    
    

